version: "3"
services:
  serve:
    container_name: video-serve
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    expose:
      - 5000
    restart: always
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
